---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/courses":
    get:
      summary: get all courses
      tags:
      - Courses
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: integer
                    duration:
                      type: integer
                    img_url:
                      type: string
                    instructor:
                      type: string
                  required:
                  - id
                  - title
                  - description
                  - price
                  - duration
                  - img_url
                  - instructor
    post:
      summary: create new course
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: integer
                duration:
                  type: integer
                img_url:
                  type: string
                instructor:
                  type: string
              required:
              - title
              - description
              - price
              - duration
              - img_url
              - instructor
  "/api/courses/{id}":
    parameters:
    - name: id
      in: path
      description: Course ID
      required: true
      schema:
        type: integer
    get:
      summary: get a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        description: Course ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: integer
                  duration:
                    type: integer
                  img_url:
                    type: string
                  instructor:
                    type: string
                required:
                - id
                - title
                - description
                - price
                - duration
                - img_url
                - instructor
        '404':
          description: not found
    delete:
      summary: delete a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        description: Course ID
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/users/{user_id}/reservations":
    parameters:
    - name: user_id
      in: path
      description: User ID
      required: true
      schema:
        type: string
    get:
      summary: get reservations for a user
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    date:
                      type: string
                    city:
                      type: string
                    course:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: integer
                        duration:
                          type: integer
                        img_url:
                          type: string
                        instructor:
                          type: string
                      required:
                      - id
                      - title
                      - description
                      - price
                      - duration
                      - img_url
                      - instructor
                  required:
                  - id
                  - course
                  - date
                  - city
    post:
      summary: create new reservation
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        schema:
          type: string
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id:
                  type: integer
                user_id:
                  type: integer
                date:
                  type: string
                city:
                  type: string
              required:
              - course_id
              - user_id
              - date
              - city
  "/api/users/{user_id}/reservations/{id}":
    parameters:
    - name: user_id
      in: path
      description: User ID
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: Reservation ID
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      tags:
      - Reservations
      parameters:
      - name: user_id
        in: path
        description: User ID
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: Reservation ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
