default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dev
  password: root

development:
  <<: *default
  database: e_learning_academy_development
 
test:
  <<: *default
  database: e_learning_academy_test

production:
  <<: *default
  database: e_learning_academy_production
  username: dev
  password: root